name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Run Docker containers
        run: |
          docker-compose up -d

      - name: Test application endpoints
        run: |
          sleep 30
          curl -f http://localhost:3000 || exit 1
          curl -f http://localhost:5000/api/tasks || exit 1
          curl -f -X POST -H "Content-Type: application/json" -d '{"to":"test@example.com","subject":"Test","text":"Test email"}' http://localhost:5000/api/email/send || exit 1

      - name: Stop and clean containers
        if: always()
        run: |
          docker-compose down -v
          docker image prune -f

      - name: Tag and push images to Docker Hub
        run: |
          docker tag todo-list-server localhost:5000/todo-list-server:latest
          docker tag todo-list-client localhost:3000/todo-list-client:latest
          docker tag todo-list-server ${{ secrets.DOCKERHUB_USERNAME }}/todo-list-server:latest
          docker tag todo-list-client ${{ secrets.DOCKERHUB_USERNAME }}/todo-list-client:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-list-server:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-list-client:latest